version: '3.8'

services:
  vinted-notifications:
    build: .
    image: vinted-notifications-custom:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - VN_data:/app/data
      - VN_logs:/app/logs
    restart: unless-stopped

volumes:
  VN_data:
  VN_logs:
